### ISSUE TITLE
Create pages

### ISSUE THREAD

**Issue by aksr666** [Spinnen87/CodeJam-Culture-Portal#7]
- [x] Create template for directors pages.
- [x] Update Index page.
- [x] Create directors list page with filter.
- [x] Update gatsby-node file.
- [x] Create about us page.

**Comment by aksr666** [comment]
Create template for directors pages - done.

**Comment by aksr666** [comment]
Create directors list page with filter, update Index page - done.

**Comment by aksr666** [comment]
Update gatsby-node file - done.

**Comment by alexalizurchik** [comment]
Create about us page
